version: '2'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'exlog'
      POSTGRES_PASSWORD: 'exlog'
      POSTGRES_DB: 'exlog_dev'
